### ISSUE TITLE
Feature: Simple calculator page 

### ISSUE THREAD

**Issue by DarkFalc0n** [DarkFalc0n/calcu.te#1]
Create an HTML page with a simple calculator, with basic mathematical calculations.

**Comment by SomilRathore01** [comment]
Hey @DarkFalc0n can you please assign this project to me for competing in KWOC 2022.

**Comment by Baron105** [comment]
@DarkFalc0n I have created the HTML file can you please assign me this task?
Also where do I add it?

**Comment by Baron105** [comment]
@DarkFalc0n I have created a pull request for this and the length converter file. Could you please check?
I'm participating in KWoC 2022
Thanks
