### ISSUE TITLE
Adding sub-pages for different type of calculators and redirecting them to already built pages.

### ISSUE THREAD

**Issue by Hritik-Shyam-Gupta** [DarkFalc0n/calcu.te#12]
I want to add subpages for each type of calculator and redirection to those pages from the home page.
Please assign me this issue.

**Comment by DarkFalc0n** [comment]
I will put this issue on hold till there are more calculators. Meanwhile, feel free to keep adding other features.

**Comment by DarkFalc0n** [comment]
@Hritik-Shyam-Gupta Go ahead with this, assigned to you.

**Comment by Aryan8445** [comment]
I want to resolve this issue, @Hritik-Shyam-Gupta if you are not doing then please assign me this task.

**Comment by Hritik-Shyam-Gupta** [comment]
@Aryan8445 Yes you can take this issue, and I am closing this issue as you had made a pull request for the same.
