### ISSUE TITLE
Enhancement: Minimalist UI

### ISSUE THREAD

**Issue by DarkFalc0n** [DarkFalc0n/calcu.te#2]
Upgrade the current default UI to an aesthetic and minimalist one along with an appropriate color scheme

**Comment by SomilRathore01** [comment]
Hey @Riya14-dangra can you please assign this project to me for competing in KWOC 2022.

**Comment by SomilRathore01** [comment]
Hey @DarkFalc0n can you please assign this project to me for competing in KWOC 2022.
