### ISSUE TITLE
Make ft to inch to cm converter 

### ISSUE THREAD

**Issue by gupta-ekansh** [DarkFalc0n/calcu.te#3]

**Comment by DarkFalc0n** [comment]
Go ahead, make sure to add a new html file for this and link the file in the index.html.

**Comment by SomilRathore01** [comment]
Hey @DarkFalc0n can you please assign this project to me for competing in KWOC 2022.

**Comment by gupta-ekansh** [comment]
> 

sure would do the above mentioned

**Comment by SomilRathore01** [comment]
Hey @DarkFalc0n can you please assign this project to me for competing in KWOC 2022.
