### ISSUE TITLE
weight converter in kg and in pounds

### ISSUE THREAD

**Issue by NiharikaSharma18** [DarkFalc0n/calcu.te#5]
please assign this issue to me

**Comment by DarkFalc0n** [comment]
Please make a different HTML file for the weight converters and add a link to it in the homepage. Follow the contribution guidelines. Good Luck!!

**Comment by NiharikaSharma18** [comment]
sir,you haven"it assign the issue to me

**Comment by DarkFalc0n** [comment]
I assigned it to you 2 days ago, please check the thread.

**Comment by NiharikaSharma18** [comment]
Sir,i am dobmne with the task one thing I need to know where I have to put
the link of weight converter
U mean to say that in the main page i have to add a href link of weight
converter?

**Comment by DarkFalc0n** [comment]
@NiharikaSharma18 Leave it for now, just add the file, the linking of the files will be done later.

**Comment by NiharikaSharma18** [comment]
Added the file sir
